version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '1000:1000'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  back:
    depends_on: 
      - redis
    build: .
    image: example
    container_name: example
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:1000
volumes:
  redis: